#! /usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess as sbp

from cake.lib import task, puts
from tasks import *

@task
def shell(command):
    """ this task executes a custom shell command """
    puts('{magenta}>>{yellow} %s' % command)
    sbp.call(command, shell=True)
